<?php
return [
	['title' => 'Домашняя страница',
		'url' => '/',
		'parent_id' => '0',
		'position' => '0',
	],
	['title' => 'Услуги',
		'url' => 'service',
		'parent_id' => '0',
		'position' => '1',
	],
	['title' => 'Автосервис',
		'url' => 'service/avtoservis',
		'parent_id' => '2',
		'position' => '0',
	],
	['title' => 'Выгул собак',
		'url' => 'service/vygul-sobak',
		'parent_id' => '2',
		'position' => '1',
	],
	['title' => 'О нас',
		'url' => 'about',
		'parent_id' => '0',
		'position' => '2',
	],
];
