<?php
return [
	['title' => 'Домашняя страница',
		'url' => '/',
		'parent_id' => '0',
		'position' => '0',
	],
	['title' => 'Услуги',
		'url' => 'services',
		'parent_id' => '0',
		'position' => '1',
	],
	['title' => 'Автосервис',
		'url' => 'services/avtoservis',
		'parent_id' => '2',
		'position' => '0',
	],
	['title' => 'Выгул собак',
		'url' => 'services/vygul-sobak',
		'parent_id' => '2',
		'position' => '1',
	],
	['title' => 'О нас',
		'url' => 'about',
		'parent_id' => '0',
		'position' => '2',
	],
];
